[workspace]

members = [
    "crates/common/*",
    "crates/core/*",
    "crates/core/tedge_api/tedge_config_derive",
    "crates/tests/*",
    "plugins/tedge_apt_plugin",
    "plugins/tedge_dummy_plugin",
    "plugins/tedge_apama_plugin"
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = 'abort'
