communication_buffer_size = 20

plugin_shutdown_timeout_ms = 200000

[plugins]

[plugins.prod]
kind = "producer"
[plugins.prod.configuration]

[plugins.destination]
kind = "receiver"
[plugins.destination.configuration]

